Repository Pavel401/Jobs-Scraper, pull requests merged in 2024-01, with the labels that each got.

#34 Added footer
  static/base.html
Labels: IWOC2024, Medium

#40 Fixed the Navbar Sticky
  static/base.html
Labels: bug, IWOC2024, Medium

#50 greetings action corrected
  .github/workflows/greetings.yml
Labels: IWOC2024, Medium

#58 Overflow issue on Hiver Job card
  models/hiver.go
  services/hiverScrapper.go
Labels: Medium

#60 PR-title-checker.yml and json added
  .github/pr-title-checker.json
  .github/workflows/pr-title-checker.yml
Labels: IWOC2024, Hard
